apiVersion: apps/v1
kind: Deployment
metadata:
  name: treetracker-web-map-client
  namespace: webmap
  labels:
    app: treetracker-web-map-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: treetracker-web-map-client
  template:
    metadata:
      labels:
        app: treetracker-web-map-client
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: doks.digitalocean.com/node-pool
                    operator: In
                    values:
                      - microservices-node-pool
      containers:
        - name: treetracker-web-map-client
          image: greenstand/treetracker-web-map-client:TAG
          env:
            #- name: DATABASE_SCHEMA
            #  value: reporting
